name: Release on version change

on:
    push:
        paths:
            - "pyproject.toml"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            - name: install dependencies
              run: |
                  pip install toml

            - name: Extract version from pyproject.toml
              id: extract_version
              run: |
                  VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
                  echo "Extracted version: $VERSION

            - name: Read CHANGELOG.md
              id: read_changelog
              run: |
                  CHANGELOG=$(cat CHANGELOG.md)
                  echo "CHANGELOG<<EOF" >> $GITHUB_ENV
                  echo "$CHANGELOG" >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV

            - name: Create github release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: "v${{ env.VERSION }}"
                  release_name: "v${{ env.VERSION }}"
                  draft: false
                  prerelease: false
                  body: |
                      ## Changes
                      ${{ env.CHANGELOG }}